spring:
  profiles:
    active: dev
---
server:
  port: 8002
spring:
  profiles: dev # 开发环境
  application:
    name: microServiceActivity
eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true # 服务发现开关
    service-url: # 注册到哪个Eureka Server服务注册中心，集群服务注册中心时多个中间用逗号分隔
      # 单机版 Eureka 服务注册中心
      # defaultZone: http://localhost:6001/eureka

      # 集群版 Eureka 服务注册中心
      defaultZone: http://EurekaServerFirst.com:6001/eureka,http://EurekaServerSecond.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,这样在Eureka Server服务注册中心就显示设置内容，否则显示的是主机名
    prefer-ip-address: true # 设置Eureka Server服务注册中心 实例链接 可以显示IP地址

---
server:
  port: 8002
spring:
  profiles: prod # 生产环境
  application:
    name: microServiceActivity
eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true # 服务发现开关
    service-url: # 注册到哪个Eureka Server服务注册中心，集群服务注册中心时多个中间用逗号分隔
      # 单机版 Eureka 服务注册中心
      # defaultZone: http://localhost:6001/eureka

      # 集群版 Eureka 服务注册中心
      defaultZone: http://EurekaServerFirst.com:6001/eureka,http://EurekaServerSecond.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,这样在Eureka Server服务注册中心就显示设置内容，否则显示的是主机名
    prefer-ip-address: true # 设置Eureka Server服务注册中心 实例链接 可以显示IP地址