server:
  port: 5001

spring:
  application:
    name: microServiceConfigServer
  cloud:
    config:
      server:
        git: # 远程库的git地址
          uri: https://github.com/YaoZhenPeng/fsSpringCloud.git